# Use the official Python image
FROM python:3.11

WORKDIR /app/code

# Copy project
COPY ./LLQuery /app/code

# Install dependencies
COPY ./LLQuery/requirements.txt /app/code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

